const SPLASH_ENABLED = true; //set to false to disable random splash text.
const splash = document.getElementById('splash');
const quotes = [
    'Thanks for stopping by',
    'Joe mom',
    '/b/ sucks today',
    'le sigh',
    'God bless our troops, God bless America, AND GENTLEMEN... START... YOUR... ENGINES!!!',
    'Red pilled since 1987',
    'Looksmaxxing pilled since 2024, never mogging, shooting ohio on site',
    'Currently jelqing',
    'Aye wassup dude.',
    'you smell nice Owu',
    'x3 *nuzzles* *pounces on you* UwU you\'re so warm ',
    'you will get all the robux',
    'Plants vs. Zombies has a bangin\' soundtrack',
    'It\'s 106 miles to Chicago, we\'ve got a full tank of gas, half a pack of cigarettes, it\'s dark out, and we\'re wearing sunglasses. Hit it.',
    'I\'ll have 4 fried chickens and a coke',
    'We\'re on a mission from God.',
    'I hate Illinois Nazis',
    '"I\'m GladOS" - GladOS',
    'Dies ist die Bluntsmoken-Höhle',
    'アストルフォーくんは大好きです',
    'White people love clapping when the plane lands',
    'Cwcville is an awesome place to visit',
    'What a mood recovery... Kind of a Goku-get-\'em attitude. :)',
    'Behind you',
    'There are way too many of these messages',
    'SANS UNDERTALE',
    'Terraria 5.0 when?',
    'TF3 When?',
    'Portal 3 when?',
    'Styrofoam and gasoline do not mix well',
    'Shut up idiot Shinji',
    'Evangelion has a good intro',
    'ザーワルド！！！',
    'ドドドドドドドド',
    'こんにちは',
    'Oi, Josuke',
    'Caesar!!!!!!!!!!!!',
    'uwO what\'s this',
    'Don\'t give a furry a pizza',
    'Dog backwards is God',
    '"I am God" - Kanye West',
    'How much wood could a woodchuck chuck if a woodchuck could chuck wood',
    'Call me if you get lost',
    'A BOY IS A GUN*',
    'Cherry bomb the greatest fucking album since the days of sound',
    'I hate being bi-polar it\'s awesome',
    'On sight is my top track this month',
    'I\'m gonna beat Citadel real quick',
    'Tower of Deep Darkness is the greatest tower since the days of roblox',
    'Squash war',
    'Halffazbear',
    'Pesternote',
    'No memes in #general',
    'Keep it in #politics please',
    'Click to add subtitle',
    'There lived a certain man, in Russia long ago...',
    'Click the circles',
    'I wonder how many of these there are',
    'Joseph Milroy is a cool dude',
    'I\'m the biggest hypocrite of 2015',
    'The sun beamin',
    'Dr. Disrespect used to go to WGHS',
    'Fuck chromebooks',
    'R.I.P Radioshack',
    'Money trees are the perfect place for shade, and that\'s just how I feel',
    'XXXTentacion should have just not been at the store that day',
    'DAMN. is not that bad guys',
    'I don\'t mind I know they\'ll never respect the good kid, m.A.A.d city.',
    'Tsundere this, Yandere that... How about you do some Laundere',
    'I am the stone that the builder refused',
    'Find out next time on Total... Drama.. Island!!!',
    'Ground control to Major Tom, check ignition and may god\'s love be with you',
    'Brett, it\'s me, David Bowie from the movie Labyrinth',
    'Brett, it\'s me, David Bowie from the Ziggy Stardust tour',
    'The anonymous hacker known as 4chan',
    'And they say it\'s because of the internet',
    'DD form 214',
    'I Cannot Fucking Wait Til Morrissey Dies',
    'WHAT KIND OF RAPPIN\' IS THIS?',
    'ARE U HAPPY?',
    'Rappers deserve hazard pay',
    '.JPEG > .PNG',
    'I can\'t feel my face oh god, SMH no ASMR',
    'while(!(succeed = try()));',
    'mm so hungry need to find my wife and head to PF Chang\'s',
    'Memory leak? Why don\'t the users just download more RAM?',
    'Weird Fishes',
    'Machine Girl - うずまき',
    'Yeah but do you know advanced F2L?',
    'Just got a PLL skip',
    'What the hell is a "bustle in your hedgerow" anyways?',
    'Hardcore Henry is my 2nd favorite movie',
    'Steam summer sale is a wallet vacuum',
    'Part 2 is underrated and better than part 3 tbh',
    'osu! gave me covid :(',
    'I never could\'ve thought that feelings could get thrown in the air',
    'That\'s why they call me opDavi, I\'m back, I\'m back',
    'Written in 99% assembly!',
    'Written in FORTRAN',
    'Written in Holy C',
    'Runs on Temple OS!',
    'R.I.P Terry Davis',
    '1.7.10 - 1.12 is peak minecraft',
    'My headphones plugged out!',
    'I never said that I was sad, but I remember it all',
    'I Miss The Rage!',
    'When you see "seeding" just click stop',
    'p2p ft ftw ',
    'Cake at steak!',
    'Hey guys, what\'s da update?'
]

if(SPLASH_ENABLED) {
    let index = Math.floor(Math.random() * quotes.length);
    splash.innerHTML = quotes[index];
} else {
    splash.remove();
}



